

ARCHIS_DATA = [
	{"name":"Filholl the Forsaken","location":"Astrub Plains (Astrub)","respawn":60},
	{"name":"Explosive Larvawork","location":"Astrub Sewers (Astrub)","respawn":60},
	{"name":"Claud Sharpe","location":"Astrub Fields (Astrub)","respawn":60},
	{"name":"Abribus the Protector","location":"Astrub Forest (Astrub)","respawn":60},
	{"name":"Gunner Pewpew","location":"Astrub Mountains (Astrub)","respawn":60},
	{"name":"Boarnigen the Damasker","location":"Gnashville (Brakmar), Kara (Bonta)","respawn":60},
	{"name":"Cracknut the Nuisance","location":"Gnashville, Holey Forest, Steamulating Shore, Thicket of Yurbut","respawn":150},
	{"name":"Gobpuddlet the Hairy","location":"Wild Estate","respawn":150},
	{"name":"Kraken","location":"Wild Beach (Zinit), Gnashville (Brakmar)","respawn":150},
	{"name":"Sharkinoa","location":"Wild Beach (Zinit)","respawn":150},
	{"name":"Red Makhar","location":"Calamar Island","respawn":150},
	{"name":"Grizzled Auburn Boowerewolf","location":"Sadida Kingdom","respawn":150},
	{"name":"Tigri Smisse","location":"Lands of Kelba (Kelba)","respawn":150},
	{"name":"Orrokimaru the Creeper","location":"Kelba Peaks (Kelba)","respawn":150},
	{"name":"Ratafia the Unsteady","location":"Monk Island","respawn":150},
	{"name":"Rack Istley","location":"Monk Island","respawn":150},
	{"name":"The White Lady","location":"Forfut","respawn":150},
	{"name":"Schnek Sy","location":"Schnek Cave (Zinit)","respawn":150},
	{"name":"Robrrrt The Brrrave","location":"Chillberg Island","respawn":150},
	{"name":"Bow Meow Loving Whisperer","location":"Shhhudoku Kingdom","respawn":150},
	{"name":"Prince Jellu","location":"Bilbiza","respawn":150},
	{"name":"Fhenris The Lone Boohemoth","location":"Ruins of the Asparah Gorge (Chillberg Island)","respawn":150},
	{"name":"Whirlaugh","location":"Lower Slope (Zinit)","respawn":150},
	{"name":"Troolgodyte","location":"Ohwymi","respawn":150},
	{"name":"Mihmosa the Flowery","location":"Shustuft Crust","respawn":150},
	{"name":"Count Harebourg’s Image","location":"Harebourg Castle (Chillberg Island)","respawn":150},
	{"name":"Gray XIII","location":"Lower Slope (Zinit)","respawn":240},
	{"name":"Issnotmee the Innocent","location":"The Fungopole (Ohwymi)","respawn":240},
	{"name":"Lenaldix","location":"Wabbit Island","respawn":240},
	{"name":"The Zombowabbit","location":"Wabbit Tunnels (Rabbit Island)","respawn":240},
	{"name":"Wipley The Suwvivow","location":"Wabbit Island","respawn":240},
	{"name":"Raval Disciple","location":"Srambad Divine Dimension","respawn":240},
	{"name":"Sir Urh the Recluse","location":"Enurado Divine Dimension","respawn":240},
	{"name":"Roonaldo the Returner","location":"Xelorium Past Divine Dimension","respawn":240},
	{"name":"The Bird of Time","location":"Xelorium present Divine Dimension","respawn":240},
	{"name":"Sister Solder the Melted","location":"Upper Slope – Kali’s Henchmen (Zinit)","respawn":240},
	{"name":"Uhu the Honeyed","location":"Upper Slope – Badgerox (Zinit)","respawn":240},
	{"name":"Minibuliette","location":"Summit – Dreggons (Zinit)","respawn":240},
	{"name":"Freonctuous the Gaspacho","location":"Summit – Ethernals (Zinit)","respawn":240},
	{"name":"Sar’Houmane the Priest of the Flame","location":"Dor’Mor Cave (Zinit)","respawn":240}
]